# -*- coding: utf-8 -*-
"""dc_fr_r_sa_90.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WobfhkIkS0xXbnI1-IzG9V9Drg8M6XU3
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def preprocess_text(text):
    return text.replace("URL", "").replace("@USER", "").strip()

# Load the dataset
df_train = pd.read_csv("/home/aaadfg/fr/90_10/train_90.csv")
df_test = pd.read_csv("/home/aaadfg/fr/90_10/test_90.csv")

# Preprocess text
df_train['processed_tweet'] = df_train['Tweet_Text'].apply(preprocess_text)
df_test['processed_tweet'] = df_test['Tweet_Text'].apply(preprocess_text)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(max_features=1000)  # Adjust `max_features` as needed
X_train = vectorizer.fit_transform(df_train['processed_tweet']).toarray()
X_test = vectorizer.transform(df_test['processed_tweet']).toarray()

# Update this dictionary based on your dataset for multiclass
# Update this dictionary based on your dataset
encoded_dict = {"CERT": 0, "CERT/MMU": 1, "CPU": 2, "CPU/MMU": 3, "DCC": 4, "DCC/MMU": 5, "DCC/USAR": 6, "DCC/USAR/MMU": 7, "FC": 8, "FC/MMU": 9, "FC/USAR": 10, "HAZMAT": 11, "HAZMAT/MMU": 12, "MMU": 13, "Other": 14, "TEU": 15, "USAR": 16, "USAR/MMU": 17}

df_train['event'] = df_train['Secondary_Annotation'].map(encoded_dict)
df_test['event'] = df_test['Secondary_Annotation'].map(encoded_dict)

y_train = df_train['event'].values
y_test = df_test['event'].values

# Initialize and train the Decision Tree classifier for multiclass
clf = DecisionTreeClassifier(max_depth=5)  # Adjust `max_depth` as needed
clf.fit(X_train, y_train)

# Predictions on the test set
y_pred = clf.predict(X_test)

# Evaluation for multiclass
target_names = list(encoded_dict.keys())
print(classification_report(y_test, y_pred, target_names=target_names))

# Confusion Matrix Visualization
plt.figure(figsize=(12, 12))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", xticklabels=target_names, yticklabels=target_names, cmap="Blues")
plt.title('Confusion Matrix')
plt.ylabel('Actual Labels')
plt.xlabel('Predicted Labels')
plt.savefig('/home/aaadfg/fr/60_40/dc_fr_r_m_80.png')
plt.show()