# -*- coding: utf-8 -*-
"""lr_fr_r_sa_90.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpD2Euo2mKZ12-M7HGm7nTPKzHfEZdlb
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
import seaborn as sns
import matplotlib.pyplot as plt

# Function for text preprocessing
def preprocess_text(text):
    # Lowercasing, removing punctuation, and other text cleaning
    return text.replace("URL", "").replace("@USER", "").strip().lower()

# Load your dataset
df_train = pd.read_csv("/home/aaadfg/fr/90_10/train_90.csv")
df_test = pd.read_csv("/home/aaadfg/fr/90_10/test_90.csv")

# Preprocess the text data
df_train['processed_tweet'] = df_train['Tweet_Text'].apply(preprocess_text)
df_test['processed_tweet'] = df_test['Tweet_Text'].apply(preprocess_text)

# mapping for multiclass classification
encoded_dict = {"CERT": 0, "CERT/MMU": 1, "CPU": 2, "CPU/MMU": 3, "DCC": 4, "DCC/MMU": 5, "DCC/USAR": 6, "DCC/USAR/MMU": 7, "FC": 8, "FC/MMU": 9, "FC/USAR": 10, "HAZMAT": 11, "HAZMAT/MMU": 12, "MMU": 13, "Other": 14, "TEU": 15, "USAR": 16, "USAR/MMU": 17}

df_train['event'] = df_train['Secondary_Annotation'].map(encoded_dict)
df_test['event'] = df_test['Secondary_Annotation'].map(encoded_dict)

# Prepare the data
X_train = df_train['processed_tweet']
y_train = df_train['event']
X_test = df_test['processed_tweet']
y_test = df_test['event']

# Initialize the TfidfVectorizer and Logistic Regression classifier within a Pipeline
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=1000)),  # Adjust `max_features` as needed
    ('logreg', LogisticRegression(solver='lbfgs', multi_class='multinomial', max_iter=1000))
])

# Train the model
pipeline.fit(X_train, y_train)

# Make predictions
y_pred = pipeline.predict(X_test)

# Evaluate the model for multiclass classification
target_names = list(encoded_dict.keys())
print(classification_report(y_test, y_pred, target_names=target_names))

# Confusion Matrix Visualization
plt.figure(figsize=(12, 12))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=target_names, yticklabels=target_names)
plt.title('Confusion Matrix')
plt.ylabel('Actual Labels')
plt.xlabel('Predicted Labels')
plt.show()